baseurl = "https://patinajeardiente.com"
languageCode = "es-es"
paginate = 5
title = "Patinaje Ardiente"
DefaultContentLanguage = "es"
hasCJKLanguage = false
disqusShortname = "patinajeardiente-com"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "es"