baseURL = 'https://patinajeardiente.com/'
languageCode = 'es-es'
title = 'Patinaje Ardiente'
theme = 'stack'
paginate = 5
hasCJKLanguage = false

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[markup.goldmark.renderer]
  unsafe = true
  
[languages]
  [languages.es]
    contentDir = 'content/es'
    languageCode = 'es'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'Patinaje Ardiente'
    weight = 1
    [languages.de.params]
      subtitle = 'Patinaje Ardiente'
    [languages.es.params.sidebar]
      subtitle = "En este blog podras encontrar toda la información relevante sobre el proyecto Patinaje Ardiente."

  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Patinaje Ardiente'
    weight = 1
    [languages.en.params]
      subtitle = 'Patinaje Ardiente'
    [languages.en.params.sidebar]
      subtitle = "In this blog you will find all relevant information about the 'Patinaje Ardiente' project."

